[workspace]
members = ["launchpad-cli", "launchpad-macros", "launchpad-src"]
default-members = ["launchpad-cli"]
resolver = "2"


[workspace.dependencies]
launchpad-cli = { path = "launchpad-cli" }
launchpad-macros = { path = "launchpad-macros" }
launchpad-src = { path = "launchpad-src" }
