-- Your SQL goes here
CREATE TABLE IF NOT EXISTS users (
  id bigint unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT 'user',
  password VARCHAR(255) NOT NULL
)
